DROP TABLE  IF EXISTS FLIGHTINFO;
CREATE TABLE IF NOT EXISTS FLIGHTINFO(
    DRP_DATETIME TEXT, 
    ARR_DATETIME TEXT, 
    DEP_AIRPORT TEXT, 
    ARR_AIRPORT TEXT, 
    AIRLINE TEXT, 
    FLIGHTNUMBER TEXT, 
    PRICE TEXT, 
    LINK TEXT, 
    CREATEDDATE TEXT
    )